// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJAA4mZ6XxqYdYyWqmqSuk_5pYzCPiiww',
    appId: '1:759189780705:web:d23b37ab4129c11f819fa0',
    messagingSenderId: '759189780705',
    projectId: 'fruit-hub-2f6f5',
    authDomain: 'fruit-hub-2f6f5.firebaseapp.com',
    storageBucket: 'fruit-hub-2f6f5.firebasestorage.app',
    measurementId: 'G-H3S15F9NEG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvBMPTkA32zQ6oc1jImNYbqb68fYNqGu4',
    appId: '1:759189780705:android:b3a1b389f312d640819fa0',
    messagingSenderId: '759189780705',
    projectId: 'fruit-hub-2f6f5',
    storageBucket: 'fruit-hub-2f6f5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBZvaKeEavkbitoJ2mgfjJdB2zjWcKNsA',
    appId: '1:759189780705:ios:dd09f6e64e535f1e819fa0',
    messagingSenderId: '759189780705',
    projectId: 'fruit-hub-2f6f5',
    storageBucket: 'fruit-hub-2f6f5.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBZvaKeEavkbitoJ2mgfjJdB2zjWcKNsA',
    appId: '1:759189780705:ios:dd09f6e64e535f1e819fa0',
    messagingSenderId: '759189780705',
    projectId: 'fruit-hub-2f6f5',
    storageBucket: 'fruit-hub-2f6f5.firebasestorage.app',
    iosBundleId: 'com.example.fruitHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJAA4mZ6XxqYdYyWqmqSuk_5pYzCPiiww',
    appId: '1:759189780705:web:b9eca9fcf1cdb3fd819fa0',
    messagingSenderId: '759189780705',
    projectId: 'fruit-hub-2f6f5',
    authDomain: 'fruit-hub-2f6f5.firebaseapp.com',
    storageBucket: 'fruit-hub-2f6f5.firebasestorage.app',
    measurementId: 'G-1S0DQQK496',
  );
}
